[package]

name = "geohash"
version = "0.11.1-alpha.0"
authors = [ "Ning Sun <sunng@about.me>" ]
description = "Geohash implementation for Rust."
license = "MIT/Apache-2.0"
keywords = ["geohash", "gis", "geography"]
repository = "https://github.com/georust/geohash.rs"
readme = "README.md"
documentation = "https://docs.rs/geohash/"
edition = "2018"

[dependencies.fixed]
default-features = false
git = "https://github.com/encointer/substrate-fixed"
package = "substrate-fixed"
tag = "v0.5.6"

[dependencies.codec]
default-features = false
package = "parity-scale-codec"
features = ["derive"]
version = "2.0.0"

[dependencies.serde]
default-features = false
package = "serde"
features = ["derive"]
version = "1.0.101"